// Given two strings s and t which consist of only lowercase letters.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Find the letter that was added in t.

// Example:

// Input:
// s = "abcd"
// t = "abcde"

// Output:
// e

// Explanation:
// 'e' is the letter that was added.
var findTheDifference = function(s, t) {
  let ss = s.split("");
  let tt = t.split("");
  
  ss.sort();
  tt.sort();
  
  for(let i = 0;i<tt.length;i++){
      if(ss[i] !== tt[i]){
          return tt[i];
      }
  }

};
var findTheDifference1 = function(s, t) {
  let map = {};
  for(const c of s){
      map[c] === undefined ? map[c] = 1 : map[c]++;
  }
  for (const c of t){
      if(!map[c] || map[c] === 0) return c;
      map[c]--;
  }

};
var findTheDifference2 = function(s, t) {
  let c = t.charCodeAt(t.length-1);
  for(let i = 0;i<s.length;i++){
      c ^=s.charCodeAt(i);
      c ^= t.charCodeAt(i);
  }
  return String.fromCharCode(c);
};